service: sandbox-serverless-ruby

frameworkVersion: ">=2.1.0 <3.0.0"

provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
  stage: dev

functions:
  current_time:
    handler: handler.lambda_handler
    events:
      - http:
          path: ping
          method: get
